name: Trigger Repo2 Workflow
on:
  workflow_dispatch: 
  workflow_run:
    workflows: ["My Repo2 Workflow"]
    types:
      - completed

jobs:
  trigger-repo2:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Repo2 Workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: GaushiDevOps/backend-repo2
          token:  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
          # You need to create a Personal Access Token (PAT) in repo1's settings with repo scope and add it as a secret.

