# development repo
name: trigger tests in repo2
on: workflow_dispatch
jobs:
  trigger-test:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger the automated test in repo2
        uses: peter-evans/repository-dispatch@v2
        with:
          token: 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
          repository: GaushiDevOps/backend-repo2
          event-type: my-event
          client-payload: '{"github": ${{ toJson(github) }}}'
  
